sievelib/managesieve.py
now matching AUTH-TOO-WEAK, ENCRYPT-NEEDED, QUOTA/MAXSIZE and
QUOTA/MAXSCRIPTS
it closes #35
=> added / and - to error regex - closes #35

sievelib/commands.py, sievelib/tests/test_parser.py
Fixes https://github.com/tonioo/sievelib/issues/49
=> Allow single mail address in vacation

sievelib/commands.py, sievelib/factory.py, sievelib/parser.py, sievelib/tests/test_factory.py, sievelib/tests/test_parser.py
=> Added support for RFC3894.

README.rst, sievelib/commands.py, sievelib/factory.py, sievelib/parser.py, sievelib/tests/test_factory.py, sievelib/tests/test_parser.py
https://tools.ietf.org/html/rfc5232
=> Added support for imap4flags extension.

sievelib/commands.py, sievelib/factory.py, sievelib/tests/test_factory.py, sievelib/tools.py
=> Added methods to retrieve filter properties.

sievelib/commands.py, sievelib/tests/test_parser.py
Per https://tools.ietf.org/html/rfc5490#section-3.2
=> Support fileinto :create (with mailbox capability)

sievelib/commands.py, sievelib/factory.py, sievelib/tests/test_factory.py
=> factory: added support for envelope and body tests.

README.rst, sievelib/commands.py, sievelib/tests/test_parser.py
=> Better support of relational and date extensions.

sievelib/commands.py, sievelib/factory.py, sievelib/tests/test_factory.py
=> factory: added currentdate support.

sievelib/commands.py, sievelib/tests/test_factory.py, sievelib/tests/test_parser.py
=> Stop command is an action, not a control.

sievelib/commands.py, sievelib/tests/test_factory.py
=> Temp. fix for exists command export through factory.

sievelib/commands.py
=> Added "string" as valid exists arg.

sievelib/parser.py
=> Don't return entire script on unknown token.

sievelib/parser.py, sievelib/tests/test_parser.py
=> Properly match parentheses and brackets.

sievelib/parser.py, sievelib/tests/test_parser.py
=> Check if parsed command is a test one.

sievelib/parser.py, sievelib/tests/test_parser.py
=> Fixed issues with test and control arguments.

sievelib/commands.py, sievelib/factory.py, sievelib/tests/test_factory.py, sievelib/tests/test_parser.py
Amongst other things, this fixes #104, and arguably #43. Includes basic tests.
=> Assorted fixes

sievelib/factory.py, sievelib/tests/test_factory.py
=> Added support for address test in factory.

sievelib/factory.py, sievelib/tests/test_factory.py
=> Added missing require statement when using create arg with fileinto

README.rst, sievelib/commands.py, sievelib/tests/test_factory.py, sievelib/tests/test_parser.py
This PR add the notify extension to sievelib.
=> Add Notify Extension
